-- MySQL Script generated by MySQL Workbench
-- 08/05/15 23:27:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CHATME
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CHATME
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CHATME` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CHATME` ;

-- -----------------------------------------------------
-- Table `CHATME`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHATME`.`users` ;

CREATE TABLE IF NOT EXISTS `CHATME`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ChatmeID` CHAR(10) NOT NULL COMMENT '',
  `Password` VARCHAR(255) NOT NULL COMMENT '',
  `First_Name` VARCHAR(45) NOT NULL COMMENT '',
  `Last_Name` VARCHAR(45) NOT NULL COMMENT '',
  `Email` VARCHAR(255) NOT NULL COMMENT '',
  `DOB` DATE NULL COMMENT '',
  `Gender` TINYINT NULL COMMENT '',
  `MemberSince` DATE NULL  COMMENT '',
  `CurrentCity` VARCHAR(255) NULL COMMENT '',
  `HomeTown` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idusers`, `ChatmeID`)  COMMENT '',
  UNIQUE INDEX `chatmeID_UNIQUE` (`ChatmeID` ASC)  COMMENT '',
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC)  COMMENT '',
  UNIQUE INDEX `users_UNIQUE` (`idusers` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CHATME`.`isFriend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHATME`.`isFriend` ;

CREATE TABLE IF NOT EXISTS `CHATME`.`isFriend` (
  `idisFriend` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Person1` CHAR(10) NOT NULL COMMENT '',
  `Person2` CHAR(10) NOT NULL COMMENT '',
  `FriendShipStatus` TINYINT NULL COMMENT '',
  PRIMARY KEY (`idisFriend`, `Person1`, `Person2`)  COMMENT '',
  UNIQUE INDEX `Person1_UNIQUE` (`Person1` ASC)  COMMENT '',
  UNIQUE INDEX `Person2_UNIQUE` (`Person2` ASC)  COMMENT '',
  CONSTRAINT `Person1F`
    FOREIGN KEY (`Person1`)
    REFERENCES `CHATME`.`users` (`ChatmeID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Person2F`
    FOREIGN KEY (`Person2`)
    REFERENCES `CHATME`.`users` (`ChatmeID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `CHATME`.`userStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHATME`.`userStatus` ;

CREATE TABLE IF NOT EXISTS `CHATME`.`userStatus` (
  `FChatmeID` CHAR(10) NOT NULL COMMENT '',
  `status` INT NULL COMMENT '',
  PRIMARY KEY (`FChatmeID`)  COMMENT '',
  CONSTRAINT `foreignuser`
    FOREIGN KEY (`FChatmeID`)
    REFERENCES `CHATME`.`users` (`ChatmeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CHATME`.`resetpass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHATME`.`resetpass` ;

CREATE TABLE IF NOT EXISTS `CHATME`.`resetpass` (
  `FChatmeID` CHAR(10) NOT NULL COMMENT '',
  `param1` VARCHAR(15) NULL COMMENT '',
  `param2` VARCHAR(15) NULL COMMENT '',
  `param3` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`FChatmeID`)  COMMENT '',
  CONSTRAINT `Fid`
    FOREIGN KEY (`FChatmeID`)
    REFERENCES `CHATME`.`users` (`ChatmeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
